### ISSUE TITLE
installation instructions needed

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Data-Curation-Tool#4]
Please add installation instructions to the README, similar to https://github.com/scholarsportal/Dataverse-Data-Explorer#installation

Thanks!!

As I mentioned at https://github.com/IQSS/dataverse/pull/5971#issuecomment-506819151 I added the Data Curation Tool to the list of external tools. This is what I wrote:

> Data Curation Tool: a GUI for curating data by adding labels, groups, weights and other details to assist with informed reuse. See the README.md file at https://github.com/scholarsportal/Dataverse-Data-Curation-Tool for the installation instructions.

You are welcome to edit this text, of course. It hasn't been merged into "develop" yet. Right now the text is in https://github.com/lubitchv/dataverse/pull/23 which I'm suggesting can be merged into https://github.com/IQSS/dataverse/pull/5971

The idea is that the text above or something like it will appear in a future version of this page:

http://guides.dataverse.org/en/4.15/installation/external-tools.html#inventory-of-external-tools

That is to say, it would look something like this:

![Screen Shot 2019-06-28 at 1 48 16 PM](https://user-images.githubusercontent.com/21006/60361130-6eddd580-99ab-11e9-8f3c-721132c2f196.png)

**Comment by pdurbin** [comment]
Hi! Now that Dataverse 4.15.1 is out and Data Curation Tool is listed at http://guides.dataverse.org/en/4.15.1/installation/external-tools.html as in the screenshot below, it would be lovely to have installation instructions because I think this tool will be very popular! 😄 🎉 

<img width="1255" alt="Screen Shot 2019-07-11 at 9 41 04 AM" src="https://user-images.githubusercontent.com/21006/61055764-2ddcbc80-a3c0-11e9-97bf-5569b9147fd1.png">

**Comment by kaitlinnewson** [comment]
Hi @pdurbin, we still have some work to do on the tool itself as well as some usability testing, but will try to get to this soon!

**Comment by pdurbin** [comment]
@kaitlinnewson sounds good. I'm glad the README says "Note: this application is still in active development." It helps set expectations. Please let us know if there's anything you need from us. I opened https://github.com/IQSS/dataverse-ansible/issues/88 so that we can start testing the Data Curation Tool from newly spun up installations of Dataverse some day. That way we can test the tool with arbitrary branches of Dataverse code, even code that hasn't been merged yet. It could be code that you or @lubitchv are working on within Dataverse, for example.

**Comment by lubitchv** [comment]
@pdurbin I added installation instructions for Data Curation Tool. Please find it here: [https://github.com/scholarsportal/Dataverse-Data-Curation-Tool](https://github.com/scholarsportal/Dataverse-Data-Curation-Tool)

**Comment by pdurbin** [comment]
@lubitchv looks great! Thanks! Closing! I'm going to open a new issue about supporting future releases of Dataverse but for Dataverse 4.16 and below this looks good!
