### ISSUE TITLE
Add proportion

### ISSUE THREAD

**Issue by djbrooke** [scholarsportal/Dataverse-Data-Curation-Tool#6]
Consider showing the proportion (%age) as well as count. This could be a column to the right or left of count, or some other solution.

![Screen Shot 2019-08-06 at 10 52 53 AM](https://user-images.githubusercontent.com/7773392/62564434-d01e8180-b852-11e9-8e0b-b60a982be83f.png)

**Comment by lubitchv** [comment]
Hi @djbrooke, I added proportion column  (percentage of total count) to the view. You can see it here.
[https://scholarsportal.github.io/Dataverse-Data-Curation-Tool/?dfId=40620&siteUrl=https://dataverse.scholarsportal.info](https://scholarsportal.github.io/Dataverse-Data-Curation-Tool/?dfId=40620&siteUrl=https://dataverse.scholarsportal.info) Let me know if you think something else needed to changed.

**Comment by djbrooke** [comment]
Thanks @lubitchv !!!

cc: @steventbrooke
