### ISSUE TITLE
{"status":"ERROR","message":"Unknown reserved word: {localeCode}"}

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Data-Curation-Tool#8]
When I try to use https://github.com/scholarsportal/Dataverse-Data-Curation-Tool/blob/9d14dde6ee0482d3dea63656f28bbe8ad1dba7e5/DataCuration.json I get the following error:

{"status":"ERROR","message":"Unknown reserved word: {localeCode}"}

Removing this fixed it:

     {
        "dvLocale": "{localeCode}"
     },

I believe localeCode is coming as part of https://github.com/IQSS/dataverse/issues/6215 but it isn't here yet so it should probably be removed for now. 😄

**Comment by lubitchv** [comment]
@pdurbin Yes, localeCode is not yet there. Although we are already using it in our test installation. The pull request for #6215 is almost ready. I will probably submit it tomorrow.

**Comment by pdurbin** [comment]
Great! Thanks, @lubitchv !! 🎉 

That said, in the README for Dataverse-Data-Curation-Tool you should probably offer two "DataCuration.json" versions:

- one with localeCode for future versions of Dataverse
- one without localeCode for Dataverse 4.16 and 4.17 (almost out)

**Comment by kaitlinnewson** [comment]
Updated the README and now have two json files available.

**Comment by pdurbin** [comment]
@kaitlinnewson thanks addressing both this issue and #7 ! 🎉
